# 使用 GitHub Action 来解决手动同步到 Gitee 的问题
# 效果：github repo 代码更新之后，会自动同步至 gitee
# 使用到的 GitHub Action: https://github.com/Yikun/hub-mirror-action

# https://github.com/yi-Xu-0100/hub-mirror      # 一个用于展示如何使用这个 action 的模板仓库
# https://github.com/ShixiangWang/sync2gitee    # 一个关于如何使用这个 action 的介绍

# This is a basic workflow to help you get started with Actions

name: Gitee Mirror

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      # 配置: https://github.com/oceanopen/we_share_code/settings/secrets/actions
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key && env.dst_token && env.gitee_user
        with:
          # 必选，需要同步的 Github 用户（源）
          src: 'github/${{ github.repository_owner }}'
          # 必选，需要同步到的 Gitee 用户（目的）
          dst: 'gitee/${{ secrets.GITEE_USER }}'
          # 这里请填写与 gitee 上公钥匹配的的 ssh private key，参见：https://gitee.com/profile/sshkeys
          # https://github.com/oceanopen/we_share_code/settings/secrets/actions
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 这里请填写 gitee 的令牌，参见：https://gitee.com/profile/personal_access_tokens
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # 直接取当前项目的仓库名
          static_list: ${{ github.event.repository.name }}
          # 是否强制同步
          force_update: true
          # 账号类型：对 luban-h5 而言是 user，因为是个人项目；如果是企业项目，请填写 org，因为是组织下的项目
          # account_type: user
          # 默认为 account_type，源账户类型，可以设置为 org（组织）或者 user（用户）。
          src_account_type: "user"
          # 默认为 account_type，目的账户类型，可以设置为 org（组织）或者 user（用户）。
          dst_account_type: "user"
          # 默认为 https, 可以设置为 ssh 或者 https。当设置为 ssh 时，你需要将 dst_key 所对应的公钥同时配置到源端和目的端。
          clone_style: "https"